### Pytorch Tutorial Day One

In [1]:
import torch

In [2]:
print(torch.__version__)

2.5.1


In [3]:
if torch.cuda.is_available():
    print(f"GPU available {torch.cuda.get_device_name(0)}")
print("No GPU available")

No GPU available


##### Creating Tensor

In [4]:
# Using Empty

torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
### Using Zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
## Using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
## Using rand() -> creates 2x3 matrix and initializes values randomly between 0 to 1
torch.rand(2,3)

tensor([[0.3464, 0.3265, 0.4381],
        [0.3639, 0.6850, 0.1466]])

In [9]:
# Once again
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [8]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
## Once again
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
# using arange
print(torch.arange(0,10,2))

# Using linspace
print(torch.linspace(0,10,20))

# Using eye
print(torch.eye(5))

# using full
print(torch.full((3,3),5))

tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  0.5263,  1.0526,  1.5789,  2.1053,  2.6316,  3.1579,  3.6842,
         4.2105,  4.7368,  5.2632,  5.7895,  6.3158,  6.8421,  7.3684,  7.8947,
         8.4211,  8.9474,  9.4737, 10.0000])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


##### Tensor Shapes

In [15]:
x = torch.tensor([[1,2,3],[2,3,4]])
x

tensor([[1, 2, 3],
        [2, 3, 4]])

In [16]:
x.shape

torch.Size([2, 3])

In [ ]:
# to create a tensor  like another tensor 
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [19]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [21]:
torch.full_like(x,5)

tensor([[5, 5, 5],
        [5, 5, 5]])

In [26]:
torch.rand_like(x,dtype=torch.float16)

tensor([[0.4453, 0.7476, 0.8169],
        [0.5454, 0.0420, 0.1885]], dtype=torch.float16)

##### Mathematical Operations

In [27]:
x = torch.rand(2,2)

In [44]:
x

tensor([[0.5277, 0.2472],
        [0.7909, 0.4235]])

In [30]:
y = torch.rand(2,2)

###### Element wise operations

In [41]:
# Addition
print(x+y)

print("\n")
# Multiplication
print(x*y)

print("\n")
# Subtraction
print(x-y)

print("\n")
# Division
print(x/y)

print("\n")
# Modulus
print(x%y)

print("\n")
# Power
print(x**2)

tensor([[1.0440, 0.2831],
        [1.4385, 0.7665]])


tensor([[0.2724, 0.0089],
        [0.5122, 0.1453]])


tensor([[0.0114, 0.2113],
        [0.1433, 0.0805]])


tensor([[1.0221, 6.8883],
        [1.2212, 1.2346]])


tensor([[0.0114, 0.0319],
        [0.1433, 0.0805]])


tensor([[0.2785, 0.0611],
        [0.6255, 0.1793]])


###### Scalar operations

In [45]:
print(x+3)
print(x-3)
print(x*4)
print(x/2)
print(x**2)
print(x%0.56)

tensor([[3.5277, 3.2472],
        [3.7909, 3.4235]])
tensor([[-2.4723, -2.7528],
        [-2.2091, -2.5765]])
tensor([[2.1108, 0.9887],
        [3.1635, 1.6939]])
tensor([[0.2638, 0.1236],
        [0.3954, 0.2117]])
tensor([[0.2785, 0.0611],
        [0.6255, 0.1793]])
tensor([[0.5277, 0.2472],
        [0.2309, 0.4235]])


In [46]:
c = torch.tensor([1,-1,2,-1,2,1,1,6])

In [47]:
## absulute value
torch.abs(c)

tensor([1, 1, 2, 1, 2, 1, 1, 6])

In [50]:
torch.neg(c)

tensor([-1,  1, -2,  1, -2, -1, -1, -6])

In [2]:
x = torch.tensor([0.1,20.9,15.70])

In [5]:
torch.round(x)

tensor([ 0., 21., 16.])

In [6]:
torch.ceil(x)

tensor([ 1., 21., 16.])

In [7]:
torch.floor(x)

tensor([ 0., 20., 15.])

In [1]:
print(1+1)

2


In [3]:
torch.clamp(x,min=2,max=3)

tensor([2., 3., 3.])

##### Reduction Operation

In [12]:
y = torch.randint(low=0,high=10,size=(3,4),dtype=torch.float32)

In [13]:
y

tensor([[3., 2., 3., 5.],
        [0., 0., 8., 6.],
        [2., 8., 0., 3.]])

In [14]:
torch.sum(y)

tensor(40.)

In [15]:
# Sum along columns
torch.sum(y,dim=0)

tensor([ 5., 10., 11., 14.])

In [16]:
# Sum along rows
torch.sum(y,dim=1)

tensor([13., 14., 13.])

In [18]:
torch.mean(y)

tensor(3.3333)

In [19]:
torch.mean(y,dim=0)

tensor([1.6667, 3.3333, 3.6667, 4.6667])

In [20]:
torch.mean(y,dim=1)

tensor([3.2500, 3.5000, 3.2500])

In [21]:
torch.max(y)

tensor(8.)

In [22]:
y.min()

tensor(0.)

In [23]:
y.mean()

tensor(3.3333)

In [24]:
torch.std(y)

tensor(2.8710)

In [25]:
torch.prod(y)

tensor(0.)

In [26]:
torch.argmax(y)

tensor(6)

In [27]:
torch.max(y)

tensor(8.)

In [31]:
print(y)
print("\n")
print(f"Max value and the min value in tensor is {torch.max(y)} and {torch.min(y)} respectively, and the position of the max value and min value in tensor is {torch.argmax(y)} and {torch.argmin(y)} respectively")

tensor([[3., 2., 3., 5.],
        [0., 0., 8., 6.],
        [2., 8., 0., 3.]])


Max value and the min value in tensor is 8.0 and 0.0 respectively, and the position of the max value and min value in tensor is 6 and 4 respectively


#### Matrix Operation

In [32]:
m1 = torch.randint(10,20,(3,4))

In [37]:
m2 = torch.randint(10,20,(4,3))

In [38]:
print(m1)
print(m2)

tensor([[15, 11, 18, 15],
        [13, 14, 17, 19],
        [16, 10, 13, 13]])
tensor([[12, 17, 16],
        [10, 17, 11],
        [10, 13, 17],
        [19, 14, 18]])


In [39]:
# Multiplication
torch.matmul(m1,m2)

tensor([[755, 886, 937],
        [827, 946, 993],
        [669, 793, 821]])

In [41]:
vec1 = torch.tensor([1,2])
vec2 = torch.tensor([3,4])

In [42]:
# Dot product
torch.dot(vec1,vec2)

tensor(11)

In [44]:
#Transpose
print(m1)
print(torch.transpose(m1,0,1))

tensor([[15, 11, 18, 15],
        [13, 14, 17, 19],
        [16, 10, 13, 13]])
tensor([[15, 13, 16],
        [11, 14, 10],
        [18, 17, 13],
        [15, 19, 13]])


In [50]:
m3 = torch.randint(10,20,(4,4),dtype=torch.float32)
# Determinant of a matrix
print(torch.det(m3))

tensor(174.9998)


In [52]:
m3

tensor([[10., 11., 14., 10.],
        [14., 12., 19., 12.],
        [10., 16., 12., 15.],
        [15., 10., 17., 15.]])

In [51]:
torch.inverse(m3)

tensor([[-4.4914,  3.2286,  1.0914, -0.6800],
        [-1.4571,  1.1429,  0.4571, -0.4000],
        [ 2.7429, -1.8571, -0.7429,  0.4000],
        [ 2.3543, -1.8857, -0.5543,  0.5600]])

#### Comparision Operations

In [57]:
i = torch.randint(10,30,(3,4),dtype=torch.float32)
j = torch.randint(10,30,(3,4),dtype=torch.float32)

In [58]:
i>j

tensor([[ True,  True, False, False],
        [False,  True,  True, False],
        [ True,  True,  True, False]])

In [59]:
i<j

tensor([[False, False,  True,  True],
        [ True, False, False,  True],
        [False, False, False,  True]])

In [60]:
i==j

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [62]:
i>=j

tensor([[ True,  True, False, False],
        [False,  True,  True, False],
        [ True,  True,  True, False]])

In [63]:
i<=j

tensor([[False, False,  True,  True],
        [ True, False, False,  True],
        [False, False, False,  True]])

In [64]:
torch.log(i)

tensor([[3.1781, 3.2581, 2.5649, 2.4849],
        [2.7081, 3.0910, 2.8904, 2.4849],
        [3.0445, 3.3322, 2.3979, 2.3979]])

In [65]:
torch.exp(j)

tensor([[1.2026e+06, 4.4241e+05, 8.8861e+06, 4.4241e+05],
        [1.9573e+11, 6.5660e+07, 5.9874e+04, 1.4463e+12],
        [2.4155e+07, 1.7848e+08, 2.2026e+04, 9.7448e+09]])

In [66]:
torch.sqrt(i)

tensor([[4.8990, 5.0990, 3.6056, 3.4641],
        [3.8730, 4.6904, 4.2426, 3.4641],
        [4.5826, 5.2915, 3.3166, 3.3166]])

In [67]:
torch.sigmoid(j)

tensor([[1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000]])

In [69]:
torch.softmax(i,dim=0)

tensor([[9.5246e-01, 1.1894e-01, 6.6868e-03, 4.2232e-01],
        [1.1754e-04, 2.1785e-03, 9.9241e-01, 4.2232e-01],
        [4.7420e-02, 8.7888e-01, 9.0496e-04, 1.5536e-01]])

In [70]:
torch.relu(j)

tensor([[14., 13., 16., 13.],
        [26., 18., 11., 28.],
        [17., 19., 10., 23.]])

In [71]:
i.add_(j)

tensor([[38., 39., 29., 25.],
        [41., 40., 29., 40.],
        [38., 47., 21., 34.]])

In [74]:
print(i.relu_)

<built-in method relu_ of Tensor object at 0x0000014B0F79ECB0>


#### Copying a tensor

In [83]:
x = torch.randint(10,30,(3,4),dtype=torch.float32)
y = torch.randint(10,30,(3,4),dtype=torch.float32)

In [84]:
x==y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [85]:
x=y

In [86]:
x

tensor([[20., 14., 29., 29.],
        [17., 17., 28., 14.],
        [17., 23., 12., 11.]])

In [87]:
y

tensor([[20., 14., 29., 29.],
        [17., 17., 28., 14.],
        [17., 23., 12., 11.]])

In [88]:
x[0][2]= 21

In [90]:
print(x[0][2])
print(y[0][2])

tensor(21.)
tensor(21.)


In [91]:
l = [x,y]
for m in l:
    print(id(m))

1421757498384
1421757498384


In [92]:
x = y.clone()

In [93]:
x[0][1] = 16

In [94]:
print(x[0][1])
print(y[0][1])

tensor(16.)
tensor(14.)


In [95]:
l = [x,y]
for m in l:
    print(id(m))

1421893852432
1421757498384


In [96]:
torch.cuda.is_available()

False

#### Reshaping Tensors


In [100]:
a = torch.ones(4,4)

In [101]:
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [103]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [105]:
b = a.flatten()

In [107]:
print(b)
print(len(b))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
16


In [109]:
a.shape

torch.Size([4, 4])

In [110]:
c = torch.rand(2,3,4)

In [111]:
c.shape

torch.Size([2, 3, 4])

In [113]:
c.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [114]:
c.permute(2,1,0)

tensor([[[0.8409, 0.4863],
         [0.2824, 0.1662],
         [0.3443, 0.5007]],

        [[0.2524, 0.4292],
         [0.7919, 0.7176],
         [0.7760, 0.8563]],

        [[0.2597, 0.3795],
         [0.2053, 0.8146],
         [0.2851, 0.6414]],

        [[0.7229, 0.5837],
         [0.6295, 0.3406],
         [0.5444, 0.7904]]])

In [115]:
a = torch.rand(2,3)

In [117]:
b = a.numpy()

In [119]:
type(a)

torch.Tensor

In [118]:
type(b)

numpy.ndarray

In [120]:
import numpy as np
c = np.array([2,3,4])
type(c)

numpy.ndarray

In [121]:
d= torch.from_numpy(c)

In [122]:
type(d)

torch.Tensor