### Pytorch Tutorial Day One

In [1]:
import torch

In [2]:
print(torch.__version__)

2.5.1


In [3]:
if torch.cuda.is_available():
    print(f"GPU available {torch.cuda.get_device_name(0)}")
print("No GPU available")

No GPU available


##### Creating Tensor

In [4]:
# Using Empty

torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
### Using Zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
## Using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
## Using rand() -> creates 2x3 matrix and initializes values randomly between 0 to 1
torch.rand(2,3)

tensor([[0.3464, 0.3265, 0.4381],
        [0.3639, 0.6850, 0.1466]])

In [ ]:
# Once again
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [8]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
## Once again
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
# using arange
print(torch.arange(0,10,2))

# Using linspace
print(torch.linspace(0,10,20))

# Using eye
print(torch.eye(5))

# using full
print(torch.full((3,3),5))

tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  0.5263,  1.0526,  1.5789,  2.1053,  2.6316,  3.1579,  3.6842,
         4.2105,  4.7368,  5.2632,  5.7895,  6.3158,  6.8421,  7.3684,  7.8947,
         8.4211,  8.9474,  9.4737, 10.0000])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])
