### Pytorch Tutorial Day One

In [2]:
import torch

In [2]:
print(torch.__version__)

2.5.1


In [3]:
if torch.cuda.is_available():
    print(f"GPU available {torch.cuda.get_device_name(0)}")
print("No GPU available")

No GPU available


##### Creating Tensor

In [4]:
# Using Empty

torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
### Using Zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
## Using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
## Using rand() -> creates 2x3 matrix and initializes values randomly between 0 to 1
torch.rand(2,3)

tensor([[0.3464, 0.3265, 0.4381],
        [0.3639, 0.6850, 0.1466]])

In [9]:
# Once again
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [8]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
## Once again
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
# using arange
print(torch.arange(0,10,2))

# Using linspace
print(torch.linspace(0,10,20))

# Using eye
print(torch.eye(5))

# using full
print(torch.full((3,3),5))

tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  0.5263,  1.0526,  1.5789,  2.1053,  2.6316,  3.1579,  3.6842,
         4.2105,  4.7368,  5.2632,  5.7895,  6.3158,  6.8421,  7.3684,  7.8947,
         8.4211,  8.9474,  9.4737, 10.0000])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


##### Tensor Shapes

In [15]:
x = torch.tensor([[1,2,3],[2,3,4]])
x

tensor([[1, 2, 3],
        [2, 3, 4]])

In [16]:
x.shape

torch.Size([2, 3])

In [ ]:
# to create a tensor  like another tensor 
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [19]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [21]:
torch.full_like(x,5)

tensor([[5, 5, 5],
        [5, 5, 5]])

In [26]:
torch.rand_like(x,dtype=torch.float16)

tensor([[0.4453, 0.7476, 0.8169],
        [0.5454, 0.0420, 0.1885]], dtype=torch.float16)

##### Mathematical Operations

In [27]:
x = torch.rand(2,2)

In [44]:
x

tensor([[0.5277, 0.2472],
        [0.7909, 0.4235]])

In [30]:
y = torch.rand(2,2)

###### Element wise operations

In [41]:
# Addition
print(x+y)

print("\n")
# Multiplication
print(x*y)

print("\n")
# Subtraction
print(x-y)

print("\n")
# Division
print(x/y)

print("\n")
# Modulus
print(x%y)

print("\n")
# Power
print(x**2)

tensor([[1.0440, 0.2831],
        [1.4385, 0.7665]])


tensor([[0.2724, 0.0089],
        [0.5122, 0.1453]])


tensor([[0.0114, 0.2113],
        [0.1433, 0.0805]])


tensor([[1.0221, 6.8883],
        [1.2212, 1.2346]])


tensor([[0.0114, 0.0319],
        [0.1433, 0.0805]])


tensor([[0.2785, 0.0611],
        [0.6255, 0.1793]])


###### Scalar operations

In [45]:
print(x+3)
print(x-3)
print(x*4)
print(x/2)
print(x**2)
print(x%0.56)

tensor([[3.5277, 3.2472],
        [3.7909, 3.4235]])
tensor([[-2.4723, -2.7528],
        [-2.2091, -2.5765]])
tensor([[2.1108, 0.9887],
        [3.1635, 1.6939]])
tensor([[0.2638, 0.1236],
        [0.3954, 0.2117]])
tensor([[0.2785, 0.0611],
        [0.6255, 0.1793]])
tensor([[0.5277, 0.2472],
        [0.2309, 0.4235]])


In [46]:
c = torch.tensor([1,-1,2,-1,2,1,1,6])

In [47]:
## absulute value
torch.abs(c)

tensor([1, 1, 2, 1, 2, 1, 1, 6])

In [50]:
torch.neg(c)

tensor([-1,  1, -2,  1, -2, -1, -1, -6])

In [3]:
x = torch.tensor([0.1,20.9,15.70])

In [5]:
torch.round(x)

tensor([ 0., 21., 16.])

In [6]:
torch.ceil(x)

tensor([ 1., 21., 16.])

In [7]:
torch.floor(x)

tensor([ 0., 20., 15.])

In [1]:
print(1+1)

2
